export const DENSITY = {
  panelHeaderHeightPx: 18,
  toolbarHeightPx: 20,
  commandBarHeightPx: 22,
  rowHeightPx: 17,
  rowHeightCompactPx: 14,
  pad2: 2,
  pad4: 4,
  borderColor: '#222',
  gridlineColor: '#111',
  bgBase: '#000',
  bgSurface: '#060606',
  bgSurfaceAlt: '#0a0a0a',
  bgHeader: '#000084',
  textPrimary: '#e6e6e6',
  textDim: '#93a9c6',
  textMuted: '#555',
  accentAmber: '#FFB000',
  accentGreen: '#00c853',
  accentRed: '#d32f2f',
  accentCyan: '#63c8ff',
  accentWhite: '#fff',
  fontSizeDefault: '11px',
  fontSizeHeader: '10px',
  fontSizeMicro: '9px',
  fontSizeTiny: '8px',
  fontFamily: "'JetBrains Mono','Roboto Mono',monospace",
  scrollbarWidth: 3,
  flashDurationMs: 150,
} as const;

export type DensityTokens = typeof DENSITY;
