import type { MarketSector } from './panelState';
import { catalogToMnemonicRegistryDef, listCatalogMnemonics, searchMnemonicCatalog } from '../mnemonics/catalog';

export interface MnemonicDef {
  code: string;
  title: string;
  requiresSecurity: boolean;
  supportedSectors: MarketSector[];
  layoutType: 'table' | 'news' | 'chart' | 'form' | 'kv' | 'composite';
  relatedCodes: string[];
}

const ALL_SECTORS: MarketSector[] = ['EQUITY', 'CORP', 'CURNCY', 'COMDTY', 'INDEX', 'GOVT', 'MUNI', 'MTGE'];

export const MNEMONIC_DEFS: Record<string, MnemonicDef> = {
  WEI:  { code: 'WEI', title: 'World Equity Indices', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['IMAP', 'TOP', 'ECO'] },
  TOP:  { code: 'TOP', title: 'Top News', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['N', 'CN', 'WEI'] },
  N:    { code: 'N', title: 'News Search', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['TOP', 'CN'] },
  CN:   { code: 'CN', title: 'Company News', requiresSecurity: true, supportedSectors: ['EQUITY', 'CORP'], layoutType: 'news', relatedCodes: ['TOP', 'N', 'DES'] },
  DES:  { code: 'DES', title: 'Security Description', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'kv', relatedCodes: ['HP', 'OWN', 'FA', 'RELS', 'MGMT'] },
  HP:   { code: 'HP', title: 'Historical Pricing', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['GP', 'DES', 'DVD'] },
  DVD:  { code: 'DVD', title: 'Dividend History', requiresSecurity: true, supportedSectors: ['EQUITY'], layoutType: 'table', relatedCodes: ['HP', 'DES', 'FA'] },
  MGMT: { code: 'MGMT', title: 'Management', requiresSecurity: true, supportedSectors: ['EQUITY', 'CORP'], layoutType: 'table', relatedCodes: ['DES', 'OWN'] },
  OWN:  { code: 'OWN', title: 'Ownership', requiresSecurity: true, supportedSectors: ['EQUITY'], layoutType: 'table', relatedCodes: ['MGMT', 'DES', 'RELS'] },
  RELS: { code: 'RELS', title: 'Related Securities', requiresSecurity: true, supportedSectors: ['EQUITY', 'CORP'], layoutType: 'table', relatedCodes: ['DES', 'OWN'] },
  FA:   { code: 'FA', title: 'Financial Analysis', requiresSecurity: true, supportedSectors: ['EQUITY', 'CORP'], layoutType: 'table', relatedCodes: ['DES', 'HP'] },
  EVT:  { code: 'EVT', title: 'Corporate Events', requiresSecurity: true, supportedSectors: ['EQUITY'], layoutType: 'table', relatedCodes: ['DES', 'DVD', 'HP'] },
  GP:   { code: 'GP', title: 'Price Chart', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'chart', relatedCodes: ['GIP', 'HP', 'RV'] },
  GIP:  { code: 'GIP', title: 'Intraday Chart', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'chart', relatedCodes: ['GP', 'HP'] },
  RV:   { code: 'RV', title: 'Relative Value', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'chart', relatedCodes: ['GP'] },
  ECO:  { code: 'ECO', title: 'Economic Calendar', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WEI', 'TOP'] },
  FXC:  { code: 'FXC', title: 'FX Cross Matrix', requiresSecurity: false, supportedSectors: ['CURNCY'], layoutType: 'table', relatedCodes: ['WEI'] },
  GC:   { code: 'GC', title: 'Yield Curve', requiresSecurity: false, supportedSectors: ['GOVT', 'CORP'], layoutType: 'chart', relatedCodes: ['DES'] },
  IMAP: { code: 'IMAP', title: 'Sector Heatmap', requiresSecurity: false, supportedSectors: ['EQUITY', 'INDEX'], layoutType: 'chart', relatedCodes: ['WEI'] },
  ALRT: { code: 'ALRT', title: 'Alerts Monitor', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['TOP'] },
  BLTR: { code: 'BLTR', title: 'Blotter', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ORD'] },
  ORD:  { code: 'ORD', title: 'Order Ticket', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['BLTR'] },
  ANR:  { code: 'ANR', title: 'Analytics Runtime', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WEI'] },
  IB:   { code: 'IB', title: 'Instant Bloomberg', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: [] },
  MON:  { code: 'MON', title: 'Monitor / Watchlist', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WEI', 'ALRT'] },
  WS:   { code: 'WS', title: 'Workspace Manager', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: [] },
  NOTES:{ code: 'NOTES', title: 'Security Notes', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['DES', 'IB', 'AUD'] },
  AUD:  { code: 'AUD', title: 'Command Audit Log', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WS', 'ALRT', 'IB'] },
  NEWS: { code: 'NEWS', title: 'News Search', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['TOP', 'CN'] },
  MKT:  { code: 'MKT', title: 'Market Context', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['WEI', 'ECO', 'IMAP'] },
  STAT: { code: 'STAT', title: 'System Status & Feed Health', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['LAT', 'ERR', 'CACH'] },
  LAT:  { code: 'LAT', title: 'Latency Monitor', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['STAT', 'ERR', 'AUD'] },
  CACH: { code: 'CACH', title: 'Cache & Offline Behavior', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['STAT', 'ERR', 'WS'] },
  ERR:  { code: 'ERR', title: 'Error Console', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['STAT', 'LAT', 'AUD'] },
  ENT:  { code: 'ENT', title: 'Entitlements Matrix', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['COMP', 'POL', 'AUD'] },
  COMP: { code: 'COMP', title: 'Compliance Lock Modes', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['ENT', 'POL', 'AUD'] },
  POL:  { code: 'POL', title: 'Policy Rules Engine', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['ENT', 'COMP', 'AUD'] },
  LINE: { code: 'LINE', title: 'Data Lineage Viewer', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['FLD', 'MAP', 'QLT'] },
  FLD:  { code: 'FLD', title: 'Field Catalog Full', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['LINE', 'MAP', 'SCRN'] },
  MAP:  { code: 'MAP', title: 'Field Mapping Aliases', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['FLD', 'LINE', 'CFG'] },
  QLT:  { code: 'QLT', title: 'Data Quality Monitor', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['LINE', 'ERR', 'STAT'] },
  MAC:  { code: 'MAC', title: 'Macro Recorder', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['JOB', 'HOT', 'TPL'] },
  JOB:  { code: 'JOB', title: 'Scheduled Jobs', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['MAC', 'AUD', 'RPT'] },
  HOT:  { code: 'HOT', title: 'Hotkey Editor', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['MAC', 'TPL', 'GRID'] },
  TPL:  { code: 'TPL', title: 'Layout Templates', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WS', 'HOT', 'SHAR'] },
  RPT:  { code: 'RPT', title: 'Report Builder', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['EXP', 'GRAB+', 'CLIP'] },
  EXP:  { code: 'EXP', title: 'Export Center', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RPT', 'AUD', 'COMP'] },
  'GRAB+': { code: 'GRAB+', title: 'Screenshot + Annotation', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['EXP', 'CLIP', 'RPT'] },
  CLIP: { code: 'CLIP', title: 'Clip Library', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['GRAB+', 'RPT', 'NOTE'] },
  CHAT: { code: 'CHAT', title: 'Panel-linked Chat', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['IB', 'SHAR', 'NOTE'] },
  SHAR: { code: 'SHAR', title: 'Share Workspace / Panel', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WS', 'CHAT', 'AUD'] },
  NOTE: { code: 'NOTE', title: 'Structured Notes', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['NOTES', 'DES', 'TASK'] },
  TASK: { code: 'TASK', title: 'Desk Task List', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['NOTE', 'ALRT', 'AUD'] },
  TCA:  { code: 'TCA', title: 'Transaction Cost Analysis', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['BLTR', 'VEN', 'IMP'] },
  VEN:  { code: 'VEN', title: 'Venue Map', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['TCA', 'IMP', 'LAT'] },
  IMP:  { code: 'IMP', title: 'Impact Model', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ORD', 'TCA', 'VEN'] },
  KILL: { code: 'KILL', title: 'Kill Switch Panel', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['COMP', 'POL', 'BLTR'] },
  REG:  { code: 'REG', title: 'Regime Library', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['MKT', 'SHCK', 'XAS'] },
  SHCK: { code: 'SHCK', title: 'Shock Library', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['SCEN', 'REG', 'XAS'] },
  XAS:  { code: 'XAS', title: 'Cross-Asset Spread Board', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['REG', 'CORR+', 'MKT'] },
  'CORR+': { code: 'CORR+', title: 'Correlation Explorer', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['XAS', 'RV', 'MKT'] },
  SENT: { code: 'SENT', title: 'Sentiment Tape', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['TOP', 'WEB', 'SUPP'] },
  WEB:  { code: 'WEB', title: 'Web Signals', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['SENT', 'SUPP', 'ESG'] },
  SUPP: { code: 'SUPP', title: 'Supply Chain Signals', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RELS', 'WEB', 'SENT'] },
  ESG:  { code: 'ESG', title: 'ESG Snapshot', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['DES', 'WEB', 'DOC'] },
  DOC:  { code: 'DOC', title: 'Document Library', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['TRNS', 'EXTR', 'NOTE'] },
  EXTR: { code: 'EXTR', title: 'Entity Extraction', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['DOC', 'LINE', 'TOP'] },
  'COMP+': { code: 'COMP+', title: 'Comparable Company Pack', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RV', 'RELS', 'FA'] },
  'HIST+': { code: 'HIST+', title: 'Crisis & Drawdown Atlas', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'chart', relatedCodes: ['HP', 'GP', 'SHCK'] },
  GRID: { code: 'GRID', title: 'Universal Grid Tuner', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['THEME', 'COLS', 'PIN'] },
  THEME:{ code: 'THEME', title: 'Theme Graph', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['BASK', 'SENTR', 'RELG'] },
  COLS: { code: 'COLS', title: 'Column Sets', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['GRID', 'PIN', 'SCRN'] },
  PIN:  { code: 'PIN', title: 'Pinboard Strip', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['COLS', 'DES', 'MON'] },
  ADM:  { code: 'ADM', title: 'Admin Console', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ENT', 'CFG', 'UPD'] },
  CFG:  { code: 'CFG', title: 'Source Configuration', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['MAP', 'ADM', 'LINE'] },
  UPD:  { code: 'UPD', title: 'Update Manager', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['CFG', 'ADM', 'STAT'] },
  SEC:  { code: 'SEC', title: 'Security Session Controls', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['COMP', 'ENT', 'POL'] },
  NAV:  { code: 'NAV', title: 'Navigation Graph', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['AUD', 'NX', 'WS'] },
  NX:   { code: 'NX', title: 'Next Best Actions Engine', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['NAV', 'MENU', 'HL'] },
  GEO:    { code: 'GEO', title: 'Global Intelligence Map', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['GEO.N', 'RGN', 'RELG'] },
  'GEO.N':{ code: 'GEO.N', title: 'Geo News Heat', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['GEO', 'RGN.N', 'NMAP'] },
  'GEO.C':{ code: 'GEO.C', title: 'Company Footprint Map', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['CMPY', 'SCN', 'FAC'] },
  'GEO.R':{ code: 'GEO.R', title: 'Regional Risk Map', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['RGN.R', 'SHOCK.G', 'NET'] },
  'GEO.M':{ code: 'GEO.M', title: 'Macro Map', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['RGN.M', 'XDRV', 'BETA.X'] },
  'GEO.X':{ code: 'GEO.X', title: 'Cross-Border Exposure Map', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['SCN', 'NEX', 'SHOCK.G'] },
  'GEO.S':{ code: 'GEO.S', title: 'Supply Chain Disruption Map', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['SCN.R', 'SUPP', 'FAC'] },
  'GEO.E':{ code: 'GEO.E', title: 'Energy & Commodities Map', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['XAS', 'SHCK', 'RGN'] },
  'GEO.F':{ code: 'GEO.F', title: 'Freight & Shipping Lanes', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['GEO.S', 'SCN.R', 'NEX'] },
  'GEO.A':{ code: 'GEO.A', title: 'Alerted Regions', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['ALRT', 'RGN.R', 'GEO.R'] },
  RELG:   { code: 'RELG', title: 'Relationship Graph', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['RELT', 'EVID', 'PATH'] },
  RELT:   { code: 'RELT', title: 'Relationship Table', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RELG', 'EVID', 'NET'] },
  OUT:    { code: 'OUT', title: 'Outbound Impact', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['IMP', 'RELG', 'NET'] },
  NET:    { code: 'NET', title: 'Network Stress View', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RELG', 'EVID', 'HEDGE'] },
  EVID:   { code: 'EVID', title: 'Evidence Panel', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RELT', 'RELG', 'PATH'] },
  PATH:   { code: 'PATH', title: 'Causal Path Explorer', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['IMP', 'OUT', 'EVID'] },
  BASK:   { code: 'BASK', title: 'Basket Builder Graph-derived', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['MON', 'CORR+', 'SCEN'] },
  SENTR:  { code: 'SENTR', title: 'Sentiment Narrative Graph', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['NREL', 'SENT', 'RELG'] },
  RGN:    { code: 'RGN', title: 'Region Dossier', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['RGN.C', 'RGN.N', 'RGN.M'] },
  'RGN.C':{ code: 'RGN.C', title: 'Region Companies', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RGN', 'CMPY', 'RELG'] },
  'RGN.N':{ code: 'RGN.N', title: 'Region News Center', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['RGN', 'NMAP', 'NREL'] },
  'RGN.M':{ code: 'RGN.M', title: 'Region Macro Monitor', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RGN', 'GEO.M', 'XDRV'] },
  'RGN.R':{ code: 'RGN.R', title: 'Region Risk Register', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RGN', 'GEO.R', 'SCN.R'] },
  NMAP:   { code: 'NMAP', title: 'News Map Overlay', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['GEO.N', 'NREL', 'NQ'] },
  NREL:   { code: 'NREL', title: 'News Relationship Builder', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['NMAP', 'RELG', 'IMP'] },
  NEX:    { code: 'NEX', title: 'News Exposures', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['NREL', 'RGN.R', 'SCN.R'] },
  NTIM:   { code: 'NTIM', title: 'News Timeline with Reaction', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['NREL', 'GP', 'IMP'] },
  NQ:     { code: 'NQ', title: 'News Query Language', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'news', relatedCodes: ['NMAP', 'NREL', 'NEX'] },
  SCN:    { code: 'SCN', title: 'Supply Chain Network', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['SCN.R', 'SUPP', 'CUST'] },
  'SCN.R':{ code: 'SCN.R', title: 'Supply Chain Risk Monitor', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['SCN', 'GEO.S', 'NEX'] },
  FAC:    { code: 'FAC', title: 'Facility List Critical Sites', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['GEO.C', 'GEO.S', 'SCN'] },
  CUST:   { code: 'CUST', title: 'Customer Concentration', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['SCN', 'RELG', 'OUT'] },
  XDRV:   { code: 'XDRV', title: 'Cross-Driver Dashboard', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['BETA.X', 'IMP', 'REGI'] },
  'BETA.X':{ code: 'BETA.X', title: 'Cross-Asset Beta Matrix', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['XDRV', 'REGI', 'HEDGE'] },
  REGI:   { code: 'REGI', title: 'Regime-conditioned Relationships', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['REG', 'RELG', 'NET'] },
  HEDGE:  { code: 'HEDGE', title: 'Hedge Candidate Explorer', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['NET', 'BETA.X', 'BASK'] },
  'SHOCK.G':{ code: 'SHOCK.G', title: 'Geo Shock Simulator', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['SHCK', 'GEO.R', 'PATH'] },
  NAVG:   { code: 'NAVG', title: 'Navigation Graph Per Panel', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['NAV', 'TRAIL', 'BKMK'] },
  BKMK:   { code: 'BKMK', title: 'Bookmarks Stateful', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['NAVG', 'TRAIL', 'WS'] },
  TRAIL:  { code: 'TRAIL', title: 'Trail Recorder Session Replay', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['AUD', 'NAVG', 'BKMK'] },
  RELATE: { code: 'RELATE', title: 'Related to This Universal Action', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RELG', 'NREL', 'GEO'] },
  FOCUS:  { code: 'FOCUS', title: 'Focus Mode', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['WS', 'TPL', 'NAVG'] },
  CMPY:   { code: 'CMPY', title: 'Company Dossier', requiresSecurity: true, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['DES', 'RELG', 'GEO.C'] },
  SECT:   { code: 'SECT', title: 'Sector Dossier', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['IMAP', 'RELG', 'REGI'] },
  INDY:   { code: 'INDY', title: 'Industry Dossier', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['SECT', 'SCN', 'NET'] },
  CTY:    { code: 'CTY', title: 'Country Dossier', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['RGN', 'GEO', 'RGN.R'] },
  CITY:   { code: 'CITY', title: 'City Hub Dossier', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['CTY', 'GEO', 'NMAP'] },
  DOCK:   { code: 'DOCK', title: 'Dockable Workspace Layout Engine', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['FLOAT', 'LAYOUT', 'WS'] },
  FLOAT:  { code: 'FLOAT', title: 'Pop-out Windows Multi-monitor', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['DOCK', 'LAYOUT', 'FOCUS+'] },
  LAYOUT: { code: 'LAYOUT', title: 'Layout Templates Constraints', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['DOCK', 'WS', 'TPL'] },
  'FOCUS+': { code: 'FOCUS+', title: 'Focus Mode Quick Return', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'composite', relatedCodes: ['FOCUS', 'DOCK', 'NAVG'] },
  PINBAR: { code: 'PINBAR', title: 'Global Pin Strip HUD', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['PIN', 'DOCK', 'WS'] },
  NAVTREE:{ code: 'NAVTREE', title: 'Global Function Navigator', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['CMDK', 'MENU', 'NX'] },
  AUTH:   { code: 'AUTH', title: 'Authentication Hub', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['MFA', 'SESS', 'LOCK'] },
  MFA:    { code: 'MFA', title: 'Multi-factor + Device Trust', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['AUTH', 'SESS', 'ROLE'] },
  SESS:   { code: 'SESS', title: 'Session Manager', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['AUTH', 'MFA', 'LOCK'] },
  ROLE:   { code: 'ROLE', title: 'Roles and Permissions', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ENT', 'POLICY', 'ADMIN'] },
  PREF:   { code: 'PREF', title: 'Global Preferences', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['GRIDCFG', 'THEMEPRO', 'FORMAT'] },
  KEYMAP: { code: 'KEYMAP', title: 'Hotkey Editor + Profiles', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['CMDK', 'PREF', 'HOT'] },
  LINK:   { code: 'LINK', title: 'Pane Link Groups', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['DOCK', 'WS', 'NAVG'] },
  FORMAT: { code: 'FORMAT', title: 'Number and Time Formatting', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['PREF', 'GRIDCFG', 'THEMEPRO'] },
  CMDK:   { code: 'CMDK', title: 'Global Command Palette', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['HL+', 'NAVTREE', 'RECENT'] },
  'HL+':  { code: 'HL+', title: 'Unified Search Hub', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['CMDK', 'HL', 'RECENT'] },
  RECENT: { code: 'RECENT', title: 'Recent Everything', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['BKMK', 'TRAIL', 'WS'] },
  SNAP:   { code: 'SNAP', title: 'Workspace Snapshots', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WS', 'AUDIT', 'TRAIL'] },
  MIG:    { code: 'MIG', title: 'Layout Migration Versioned', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WS', 'UPDATE', 'SNAP'] },
  SHARE:  { code: 'SHARE', title: 'Share Pane Entity Workspace', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['SHAR', 'IB', 'AUDIT'] },
  NOTIF:  { code: 'NOTIF', title: 'Notification Center', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ROUTE', 'ALRT+', 'TASK'] },
  ROUTE:  { code: 'ROUTE', title: 'Notification Routing Rules', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['NOTIF', 'ALRT+', 'POLICY'] },
  'ALRT+':{ code: 'ALRT+', title: 'Advanced Alerts', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ALRT', 'MON+', 'NOTIF'] },
  'MON+': { code: 'MON+', title: 'Monitor Builder Worksheets', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['MON', 'FLD', 'ALRT+'] },
  ADMIN:  { code: 'ADMIN', title: 'Admin Console', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ADM', 'AUDIT', 'POLICY'] },
  AUDIT:  { code: 'AUDIT', title: 'Full Audit Trail with Replay', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['AUD', 'TRAIL', 'NAVG'] },
  POLICY: { code: 'POLICY', title: 'Policy Rules Engine Block Allow', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['POL', 'ROLE', 'DLP'] },
  DLP:    { code: 'DLP', title: 'Data Loss Prevention Controls', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['COMP', 'POLICY', 'EXP'] },
  SRC:    { code: 'SRC', title: 'Data Source Manager', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['CFG', 'MAP', 'LINE'] },
  API:    { code: 'API', title: 'API Keys + Developer Portal', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WEBHOOK', 'AUTH', 'ROLE'] },
  WEBHOOK:{ code: 'WEBHOOK', title: 'Webhooks Alerts Events', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['API', 'NOTIF', 'ROUTE'] },
  PLUG:   { code: 'PLUG', title: 'Plugin System Custom Functions', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['API', 'NAVTREE', 'DOCK'] },
  STATUS: { code: 'STATUS', title: 'System Status Ops View', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['STAT', 'DIAG', 'OFFLINE'] },
  DIAG:   { code: 'DIAG', title: 'Diagnostics Profiler', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['STATUS', 'LAT', 'ERR'] },
  OFFLINE:{ code: 'OFFLINE', title: 'Offline Mode Cached Snapshots', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['CACH', 'STATUS', 'WS'] },
  UPDATE: { code: 'UPDATE', title: 'Release Notes + Versioning', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['UPD', 'MIG', 'SNAP'] },
  HELP:   { code: 'HELP', title: 'Contextual Help Overlay', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['TUTOR', 'DOCS', 'NAVTREE'] },
  TUTOR:  { code: 'TUTOR', title: 'Guided Tutorials', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['HELP', 'DOCS', 'KEYMAP'] },
  DOCS:   { code: 'DOCS', title: 'Documentation Center', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['HELP', 'API', 'FLD'] },
  LOCK:   { code: 'LOCK', title: 'Screen Lock Quick Unlock', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['AUTH', 'SESS', 'PRIV'] },
  PRIV:   { code: 'PRIV', title: 'Privacy Controls', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['LOCK', 'CONSENT', 'COMP'] },
  CONSENT:{ code: 'CONSENT', title: 'Data Usage Compliance Notices', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['PRIV', 'SRC', 'POLICY'] },
  GRIDCFG:{ code: 'GRIDCFG', title: 'Density + Grid Calibration', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['GRID', 'PREF', 'THEMEPRO'] },
  THEMEPRO:{ code: 'THEMEPRO', title: 'Terminal Palette Contrast Tests', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'form', relatedCodes: ['THEME', 'GRIDCFG', 'PREF'] },
  GMOV:   { code: 'GMOV', title: 'Global Movers Always-on Table', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WEI', 'SECH', 'RFCM'] },
  SECH:   { code: 'SECH', title: 'Sector Heat Dense Block', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['WEI', 'GMOV', 'NINT'] },
  RFCM:   { code: 'RFCM', title: 'Rates Fx Commod Snapshot', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['CRSP', 'XAS', 'ECO'] },
  CRSP:   { code: 'CRSP', title: 'Credit Spreads Snapshot', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['RFCM', 'STATUS', 'RISK'] },
  NINT:   { code: 'NINT', title: 'News Intensity and Impacted Tickers', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['TOP', 'CN', 'NREL'] },
  CAL24:  { code: 'CAL24', title: 'Calendar Next 24h', requiresSecurity: false, supportedSectors: ALL_SECTORS, layoutType: 'table', relatedCodes: ['ECO', 'NTIM', 'ALRT'] },
};

for (const c of listCatalogMnemonics()) {
  if (!MNEMONIC_DEFS[c.code]) {
    MNEMONIC_DEFS[c.code] = catalogToMnemonicRegistryDef(c);
  }
}

export function getMnemonicDef(code: string): MnemonicDef | undefined {
  return MNEMONIC_DEFS[code.toUpperCase()];
}

export function getRelatedMnemonics(code: string): MnemonicDef[] {
  const def = getMnemonicDef(code);
  if (!def) return [];
  return def.relatedCodes.map((c) => MNEMONIC_DEFS[c]).filter(Boolean) as MnemonicDef[];
}

export function searchMnemonics(query: string): MnemonicDef[] {
  const q = query.trim();
  if (!q) return Object.values(MNEMONIC_DEFS);
  const primary = Object.values(MNEMONIC_DEFS).filter((m) =>
    `${m.code} ${m.title} ${m.relatedCodes.join(' ')}`.toUpperCase().includes(q.toUpperCase()),
  );
  const catalog = searchMnemonicCatalog(q).map((m) => MNEMONIC_DEFS[m.code]).filter(Boolean) as MnemonicDef[];
  return Array.from(new Set([...primary, ...catalog]));
}
