// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oeosfycqhpsripaihaqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lb3NmeWNxaHBzcmlwYWloYXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMzU1NTksImV4cCI6MjA4NTkxMTU1OX0.N5njoImBsKRXPOmAjVK0z7vzq7ngjd-YiX6js1ikoKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);